FROM python:3.12.7-slim

COPY backend_requirements.txt /tmp/
RUN pip install -r /tmp/backend_requirements.txt
# RUN pip install scikit-learn scipy numpy pandas simplejson flask flask-cors gunicorn 
# RUN python -m pip install statsmodels
# RUN python -m pip install -i https://pypi.anaconda.org/scientific-python-nightly-wheels/simple statsmodels --upgrade --use-deprecated=legacy-resolver

