FROM python:3.13-slim

RUN pip install scikit-learn scipy numpy pandas simplejson flask flask-cors gunicorn 
RUN python -m pip install statsmodels
# RUN python -m pip install -i https://pypi.anaconda.org/scientific-python-nightly-wheels/simple statsmodels --upgrade --use-deprecated=legacy-resolver

