services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 4343:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/ssl/
  service1:
    image: rawmind/web-test
    container_name: myservice
    ports:
      - '127.0.0.1:8080:8080'
